spring:
  application:
    name: eureka-service

server:
  port: 8302

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

zuul:
  prefix: /api
  routes:
    cart-service:
      path: /cart-service/**
      url: http://localhost:8300
    product-service:
      path: /product-service/**
      url: http://localhost:8301
    promotion-service:
      path: /promotion-service/**
      url: http://localhost:8303